version: "3.7"

services:
  code_search_demo:
    build: .
    container_name: code_search_demo
    environment:
      - QDRANT_URL
      - QDRANT_API_KEY
    networks:
      - qdrant-net

networks:
  qdrant-net:
    external:
      name: qdrant-net
